apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: cakephp-mysql-persistent
  template: cakephp-mysql-persistent
message: |-
  The following service(s) have been created in your project: ${NAME}, ${DATABASE_SERVICE_NAME}.

  For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/cakephp-ex/blob/master/README.md.
metadata:
  annotations:
    description: An example CakePHP application with a MySQL database. For more information
      about using this template, including OpenShift considerations, see https://github.com/sclorg/cakephp-ex/blob/master/README.md.
    iconClass: icon-php
    openshift.io/display-name: CakePHP + MySQL
    openshift.io/documentation-url: https://github.com/sclorg/cakephp-ex
    openshift.io/long-description: This template defines resources needed to develop
      a CakePHP application, including a build configuration, application deployment
      configuration, and database deployment configuration.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
    samples.operator.openshift.io/version: 4.6.17
    tags: quickstart,php,cakephp
    template.openshift.io/bindable: "false"
  creationTimestamp: "2020-05-07T14:18:26Z"
  labels:
    samples.operator.openshift.io/managed: "true"
  name: cakephp-mysql-persistent
  namespace: openshift
  resourceVersion: "532091921"
  selfLink: /apis/template.openshift.io/v1/namespaces/openshift/templates/cakephp-mysql-persistent
  uid: 0a9cbf74-a242-42a5-bc3c-5b972f8bebbc
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}
    namespace: ${BUILD_NAMESPACE}
    annotations:
      description: Keeps track of changes in the application image
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
    namespace: ${BUILD_NAMESPACE}
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit:
      script: ./vendor/bin/phpunit
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: COMPOSER_MIRROR
          value: ${COMPOSER_MIRROR}
        from:
          kind: ImageStreamTag
          name: php:${PHP_VERSION}
          namespace: ${NAMESPACE}
      type: Source
    triggers:
    - type: ConfigChange
parameters:
- name: BUILD_NAMESPACE
  displayName: Build Namespace
  description: >-
    The OpenShift Namespace where the ImageStream and BuildConfig reside.
  required: true
  value: cakephp-example-build
- name: NAME
  description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  required: true
  value: cakephp-mysql-persistent
- name: NAMESPACE
  description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  required: true
  value: openshift
- name: PHP_VERSION
  description: Version of PHP image to be used (7.3-ubi7, 7.3-ubi8, or latest).
  displayName: PHP Version
  required: true
  value: 7.3-ubi8
- name: MEMORY_LIMIT
  description: Maximum amount of memory the CakePHP container can use.
  displayName: Memory Limit
  required: true
  value: 512Mi
- name: MEMORY_MYSQL_LIMIT
  description: Maximum amount of memory the MySQL container can use.
  displayName: Memory Limit (MySQL)
  required: true
  value: 512Mi
- name: VOLUME_CAPACITY
  description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume Capacity
  required: true
  value: 1Gi
- name: SOURCE_REPOSITORY_URL
  description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  required: true
  value: https://github.com/sclorg/cakephp-ex.git
- name: SOURCE_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
- name: CONTEXT_DIR
  description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the CakePHP service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
- name: GITHUB_WEBHOOK_SECRET
  displayName: Database Service Name
  description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
- name: DATABASE_SERVICE_NAME
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  required: true
  value: mysql
- name: DATABASE_ENGINE
  description: 'Database engine: postgresql, mysql or sqlite (default).'
  displayName: Database Engine
  required: true
  value: mysql
- name: DATABASE_NAME
  displayName: Database Name
  required: true
  value: default
- name: DATABASE_USER
  displayName: Database User
  required: true
  value: cakephp
- name: DATABASE_PASSWORD
  displayName: Database Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  description: Set this to a long random string.
- name: CAKEPHP_SECRET_TOKEN
  displayName: CakePHP secret token
  from: '[\w]{50}'
  generate: expression
- name: CAKEPHP_SECURITY_SALT
  description: Security salt for session hash.
  displayName: CakePHP Security Salt
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: OPCACHE_REVALIDATE_FREQ
  description: How often to check script timestamps for updates, in seconds. 0 will
  displayName: OPcache Revalidation Frequency
  value: "2"
- name: COMPOSER_MIRROR
  description: The custom Composer mirror URL
  displayName: Custom Composer Mirror URL
- name: MYSQL_DEFAULT_AUTHENTICATION_PLUGIN
  description: 'The custom MySQL default authentication plugin (default: mysql_native_password),
    might be changed to caching_sha2_password once PHP client supports it.'
  displayName: MySQL authentication plugin
  value: mysql_native_password
